### PR TITLE
feature: Adds text to CharactersChange

### PR DESCRIPTION
**Pull request by paulofaria**

### CODE REVIEW

**Comment by vmanot** [comment]
@paulofaria thanks for opening up the PR! Curious as to why you'd need this - wouldn't it be possible to access the text through whatever `Binding` you've passed to `CocoaTextField` in its initializer?

**Comment by paulofaria** [comment]
It is possible, and that is what I was doing. However, I had a crash when converting the `NSRange` parameter to `Swift.Range` using the string from the binding because the contained text was different. Probably because the binding updates after the delegate is called.

**Comment by paulofaria** [comment]
Had the exact same thoughts. I'll update the PR.

**Comment by paulofaria** [comment]
Done!

**Review by vmanot — APPROVED** [review]

**Pull request merged**
