### PR TITLE
Disable SwiftUI.HoverEffect

### LINKED ISSUE #104: Crash on iOS 13.3
I'm seeing a crash on iOS 13.3 after including this package.

`symbol '_$s7SwiftUI4ViewPAAE11hoverEffectyQrAA05HoverE0VFQOMQ' not found, expected in '/System/Library/Frameworks/SwiftUI.framework/SwiftUI`

```
Date/Time:           2020-07-23 12:37:52.5734 -0700
Launch Time:         2020-07-23 12:37:52.4878 -0700
OS Version:          iPhone OS 13.3.1 (17D50)
Release Type:        User
Baseband Version:    9.40.01
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, symbol '_$s7SwiftUI4ViewPAAE11hoverEffectyQrAA05HoverE0VFQOMQ' not found, expected in '/System/Library/Frameworks/SwiftUI.framework/SwiftUI', needed by '/private/var/containers/Bundle/Application/104AA6BE-3DDE-45F7-9569-53C0F78DAA93/xxx.app/xxx'
Highlighted by Thread:  0

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000004   x2: 0x000000016bdb6080   x3: 0x00000000000000dd
    x4: 0x000000016bdb5c80   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x392d374635342d45  x11: 0x304333352d393635
   x12: 0x304333352d393635  x13: 0x3339414144383746  x14: 0x70612e786570412f  x15: 0x0027786570412f70
   x16: 0x0000000000000209  x17: 0x0000000104ea6e50  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016bdb5c80  x21: 0x00000000000000dd  x22: 0x000000016bdb6080  x23: 0x0000000000000004
   x24: 0x0000000000000006  x25: 0x0000000104ea8000  x26: 0x0000000000000000  x27: 0x0000000104ea8000
   x28: 0x0000000000000000   fp: 0x000000016bdb5c50   lr: 0x0000000104e92498
    sp: 0x000000016bdb5c10   pc: 0x0000000104e8b5e4 cpsr: 0x00000000
   esr: 0x00000000  Address size fault

Binary images description not available

Error Formulating Crash Report:
Failed to create CSSymbolicatorRef - corpse still valid ¯\_(ツ)_/¯

EOF
```

### PR DESCRIPTION
**Pull request by AndrewSB**
Fixes #104

### CODE REVIEW

**Comment by AndrewSB** [comment]
I haven't looked to see why this crashes, but commenting out this code fixes the crash on launch

**Comment by BenSova** [comment]
I don't know if this would have any effect, but some of the `@available`s use iOS 13, not 13.4.
Maybe change all `@available(iOS 13, *)` to `@available(iOS 13.4, *)` in those two files.
This is just a guess but it might help.

**Comment by AndrewSB** [comment]
that sounds sensical, were hover effects only introduced in iOS 13.4?

**Comment by vmanot** [comment]
Hey @AndrewSB, see #51 for a possible resolution.

**Comment by Brett-Best** [comment]
I think we should update the README to include this extra step under installation.

**Comment by BenSova** [comment]
iPadOS 13.4 was when mouse support was added, along with mouse hover effects, so yes.

**Pull request closed without merging**
