### PR TITLE
Added support of enums with associated types to SwitchOver

### PR DESCRIPTION
**Pull request by maximkrouk**
Screen Recording 2020-04-03 at 11 56 57

### CODE REVIEW

**Comment by vmanot** [comment]
This is an excellent PR - would it be possible to extract the external dependency into a single file? I've been wanting this feature for a while myself, and love the implementation, but I'm looking to keep SwiftUIX as light and atomic as possible.

**Comment by maximkrouk** [comment]
Ok, I’ll check the license and extract the implementation, but light and atomic are antonyms, you know 🌚
Anyway I’m glad to see your approval, yippee 🥳

**Comment by vmanot** [comment]
@maximkrouk hahaha, I meant atomic in the sense that I want it to be a single dependency and not multiple implicit ones. And yes, I'm very much for powerful feature additions to the library - and this seems like a natural fit!

**Comment by maximkrouk** [comment]
✅ Done.

**Comment by vmanot** [comment]
I'll be revamping the `SwitchOver` API in a bit - will incorporate this when that happens. Sorry for the delay on replying to this, and great work!

**Pull request closed without merging**
