### PR TITLE
Add docs folder for easily wiki contributing

### LINKED ISSUE #80: Cannot contribute to the wiki
This library is great, but not enough documented.  
How do I editing document in the Wiki?

### PR DESCRIPTION
**Pull request by BenSova**
I added a folder called `docs`, a direct mirror of the wiki. This allows people to open a pull request containing suggested changes to the documentation. Then, @vmanot would have to copy the changes. Still not the most practical, but probably better than uploading files in issues or empty pull requests. Plus, the people who make changes would be recognized.
This fixes #80.

There are all the wiki files in the docs folder, plus a README explaining how to contribute.

If I should make any changes, let me know.

### CODE REVIEW

**Comment by BenSova** [comment]
@vmanot What do you think? I saw in the README that volunteers are needed for the wiki and after the [issue](https://github.com/SwiftUIX/SwiftUIX/issues/80), I thought this would help. I know you'd still have to move files to the wiki, but it'd help.

**Comment by vmanot** [comment]
@BenSova is there any way we can auto-generate this docs folder from the existing wiki?

**Comment by BenSova** [comment]
@vmanot not that I know of.

**Comment by vmanot** [comment]
@BenSova this is an interesting approach though - I'm still looking to see if there are better solutions. Check this article out - https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html (I'm going through it as well right now).

**Comment by BenSova** [comment]
@vmanot Another thing that might work is using a third-party documentation service, like [GitBook](https://gitbook.com). Then, you could set up a GitHub integration and people could contribute through that. 

[Electron Forge](https://www.electronforge.io/)
[My Test Wiki](https://swiftstars.gitbook.io)

If you do that, I have a few tips before you do anything.

**Comment by vmanot** [comment]
@BenSova I think I've found a solution! - https://github.com/marketplace/actions/publish-to-github-wiki

**Comment by vmanot** [comment]
@BenSova this incorporates your initial solution whilst also automating syncing to the wiki.

**Comment by BenSova** [comment]
@vmanot I agree. That'd definitely work.

**Comment by BenSova** [comment]
@vmanot This is off-topic, but the action reminded me something. 
You should add a CI check to SwiftUIX. It'd help catch things like #79, and check each commit and pull request.

You'd just have to add a file to .github/workflows/ci.yml
```yml
name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Package
      run: swift build -v
```

**Comment by vmanot** [comment]
@BenSova great point. I'll be incorporating both build checks + wiki syncing in a couple of days.

**Comment by vmanot** [comment]
@BenSova closing this PR for now, issue will remain open until documentation is editable. Thanks for all the help :)

**Comment by BenSova** [comment]
@vmanot Would you like me to hold on to my fork? I looked over the code of the action and it appears to need the wiki already inside the code, otherwise it will wipe the wiki (just a guess).

**Pull request closed without merging**
