### PR TITLE
Expose `onOffsetChange` for `PaginationView`

### PR DESCRIPTION
**Pull request by denandreychuk**
I'm not sure if I done it correctly, but my main goal is to receive content offset for PaginationView

### CODE REVIEW

**Comment by denandreychuk** [comment]
@vmanot did you have time to look into this?

**Comment by vmanot** [comment]
@denandreychuk let me fix this by the weekend.

**Comment by denandreychuk** [comment]
@vmanot any updates on this?

**Review by vmanot — APPROVED** [review]

**Comment by vmanot** [comment]
@denandreychuk sorry about the delay! Merged.

**Pull request merged**
