### PR TITLE
Support custom indicator images for PageControl (Closes #474)

### LINKED ISSUE #474: Support for custom indicator images for PageControl.
I am working on implementing this as I need it for my project. Will submit a PR when it's done.

[Apple Developer Docs: Managing the indicator images](https://developer.apple.com/documentation/uikit/uipagecontrol#4012967)

iOS 14+ added an API to UIPageControl that allows you to:
- Change the indicator image for a specific page of a UIPageControl. 
- Change the default image that all pages use unless overridden.

iOS 16+ also added the ability to:
- Pick an indicator image that will be dynamically swapped to when a specific page is active.
- Pick a default image that all pages will swap to when they are active, unless overridden.

### PR DESCRIPTION
**Pull request by fralsal**
Hi. The goal of this PR is to implement the API for indicator image management introduced in iOS 14.0 / 16.0, [as documented here.](https://developer.apple.com/documentation/uikit/uipagecontrol#4012967)
If anything needs to be revised I would be glad to help.

### CODE REVIEW

**Comment by fralsal** [comment]
Amended to allow nil values for indicator images. This matches the UIPageControl API and is documented as the way to reset an indicator back to the default.

**Comment by vmanot** [comment]
@fralsal can you update this to use `_AnyImage` instead of `UIImage`?

**Comment by fralsal** [comment]
Sure, I’ll fix it up and commit tomorrow

**Comment by vmanot** [comment]
@fralsal closing this due to inactivity, feel free to reopen if you get the time to make the update!

**Pull request closed without merging**
