### PR TITLE
Optimise hidden view modifier to avoid unnecessary branches

### PR DESCRIPTION
**Pull request by shawnkoh**
Refer to https://developer.apple.com/videos/play/wwdc2021/10022
38:00 - 39:30

The section on Structural Identity.

### CODE REVIEW

**Comment by jevonmao** [comment]
Hey Shawn! I know you from the Swift Discord server. Aside from the shoutout, I like this PR because it prevents the loss of state when hiding views.

**Comment by vmanot** [comment]
@shawnkoh @jevonmao I actually already have a modifier for this, called `visible`. The reason why I made this modifier as well was to keep the option of using `.hidden()` in case it had any special semantics over just setting the opacity to 0, but I think I may deprecate it now. Closing this PR as `View/visible(_:)` already provides this exact functionality, but thanks for highlighting it! :)

**Comment by shawnkoh** [comment]
> @shawnkoh @jevonmao I actually already have a modifier for this, called `visible`. The reason why I made this modifier as well was to keep the option of using `.hidden()` in case it had any special semantics over just setting the opacity to 0, but I think I may deprecate it now. Closing this PR as `View/visible(_:)` already provides this exact functionality, but thanks for highlighting it! :)

Ooh! May I ask why it's performed using a view modifier rather than just using the .opacity() view modifier directly?

**Comment by jevonmao** [comment]
@shawnkoh I looked over the source code, and it just seems like redundancy (whether unintentional or intentional) and can be improved. The extra modifier struct don't seem to serve any purpose, you can probably open a PR to fix it. At least this is my opinion.

**Pull request closed without merging**
