### PR TITLE
Add ShowsIndicators Function to CocoaList

### PR DESCRIPTION
**Pull request by Overcot**

### CODE REVIEW

**Comment by vmanot** [comment]
@Overcot I'm not sure whether this is the most Apple-like way to expose this API, given that `ScrollView` in SwiftUI takes in "showsIndicators" in its initializer and not as a view modifier. Thoughts?

**Comment by Overcot** [comment]
Your point makes sense but also, we better stay with 
```swift
var scrollViewConfiguration = CocoaScrollViewConfiguration
``` 
which is neat way to store everything related to scrollView configuration. If we to move `showsIndicators` inside all inits, in my opinion it will introduce a lot of unrelated boilerplate code which is not very convenient to support in future. 

For me, `ScrollView` api in SwiftUI is very-very poor and IMO more appropriate comparison will be with `Button` and `NavigationView`. They both have `.smthStyle()` function to configure their appearance. 
We could also this technique to provide function which does same. 
For example, for `CocoaList` it could be
```swift
public func listStyle(_ style: CocoaScrollViewStyle) -> Self
```
or

```swift
public func listConfiguration(_ configuration: CocoaScrollViewConfiguration) -> Self
```
and provide api users with `init` for `CocoaScrollViewConfiguration`.
But in my opinion this option in future could slow down implementing new properties (if needed) for `CocoaScrollViewConfiguration`. I know that api for SwiftUIX is not stable and subject to change at any time but still a point to consider.

What I do like in your approach is using simple functions that change only one property. If api user ever needs to call several of them he can create his own `ViewModifier` with wrapper around them. Your approach is quite flexible to add new features to configuration and that's why I implemented this feature this way

**Comment by vmanot** [comment]
@Overcot you're spot on with the "style" suggestion, I was thinking something more general - scroll indicator list styles. For example - `HiddenScrollViewIndicatorStyle(horizontal: true|false, vertical: true|false)` (similar naming to `HiddenTitleBarWindowStyle`). What do you think?

**Comment by vmanot** [comment]
As for the `scrollViewConfiguration` - I'm making it even more flexible by moving it to `EnvironmentValues` (just like I've done for `CollectionView`). Applying `HiddenScrollViewIndicatorStyle` could simply transform the environment and set the required properties, without needing any further boilerplate/modifications to `CocoaList`.

**Comment by Overcot** [comment]
so you think about moving from
```swift
        showsVerticalScrollIndicator = configuration.showsIndicators
        showsHorizontalScrollIndicator = configuration.showsIndicators
```
to 
```swift
        showsVerticalScrollIndicator = showsVerticalScrollIndicator
        showsHorizontalScrollIndicator = showsHorizontalScrollIndicator
```
?
I Guess your approach could work. 
Aren't you afraid creating multiple non interfering styles protocols for each view style configuration? 
IMO for me these swiftUI Styles are not neccessarily the best api that they created. They just create method
```swift
  func style(Style) -> Self
```
and then create multiple structs that users can create and not necessarily create custom themselves. I guess that they went with this approach instead of enums to not deal with @unknown but meh, I would I prefer cases instead of empty Structs, but I guess we stuck with it.

So for me I don't mind creating `HiddenScrollViewIndicatorStyle` based api but I would like to discuss its interface.

So we create, for example
```swift
public protocol IndicatorStyle {}
```

Then we create one or two style(s)
```swift
public struct HiddenScrollViewIndicatorStyle: IndicatorStyle {
  public init()
}
```

And there im lost :)

**Comment by SapaTech** [comment]
@vmanot hi, please add showIndicator to next update

**Comment by Overcot** [comment]
I guess I can finish this PR if I understand idea behind @vmanot comments)

**Comment by vmanot** [comment]
@SapaTech @Overcot hey folks, will have this fixed in a day. I've got a slightly different implementation in the works which supersedes this PR, so will close it once I push my changes tomorrow. Thank you for the great work @Overcot!

**Comment by vmanot** [comment]
@SapaTech @Overcot this is now fixed with a `HiddenScrollIndicatorStyle`!

**Pull request closed without merging**
