### PR TITLE
onChange Implementation and Compatible with iOS13

### PR DESCRIPTION
**Pull request by swiftyui**
## Description 

This MR is an implementation of iOS 14 `onChange`, which is compatible with iOS13.

## Features:

- Both oldValue and newValue
- Support watch on @State, @Binding, and stored/computed properties

## How to Use

```swift
struct WatchPatternDetails: View {
    
    var name: String = "Json"
    @State private var address: String = "Australia"
    @Binding var selected: Bool
    
    @State private var count = 0
    
    var body: some View {
        VStack(alignment:.leading) {
            Toggle("Toggle Test", isOn: $selected)
            Button("Click to change state") {
                count += 1
                self.address = "\(address)\(count)"
            }
        }.onChange(of: name) { (oldValue, newValue) in
            //watch stored property
            print(oldValue ?? "NA", newValue)
        }.onChange(of: address) { (oldValue, newValue) in
            //watch @State
            print(oldValue ?? "NA", newValue)
        }.onChange(of: selected) { (oldValue, newValue) in
            //watch @Binding
            print(oldValue ?? "NA", newValue)
        }
    }
}
```

### CODE REVIEW

**Comment by vmanot** [comment]
@swiftyui this is some great work! Could you please adapt it and replace the contents of [this file](https://github.com/SwiftUIX/SwiftUIX/blob/master/Sources/Intermodular/Helpers/SwiftUI/View.onChange+.swift) with your implementation?

Please also ensure that it compiles for all targets, and also works on the latest public Xcode release (Xcode 11.6, GM).

**Comment by swiftyui** [comment]
Please review again, i also added a demo here : https://github.com/swiftyui/xPriceButton

**Comment by vmanot** [comment]
@swiftyui it looks good, but it must have exact parity with the iOS 14 `onChange` implementation. Please also revert the change in `LinkPresentationView`.

**Comment by vmanot** [comment]
Closing due to inactivity. Feel free to reopen whenever you can make those changes :)

**Pull request closed without merging**
